///MARK: Home screen actions
export default AUTH_ACTIONS = {
  GET_PREVIOUS_LOGIN: "AUTH.GET_PREVIOUS_LOGIN",
  START_BIOMETRIC: "AUTH.START_BIOMETRIC",
  LOGIN: "AUTH.LOGIN",
  LOGOUT: "AUTH.LOGOUT",
  SUCCESS: "AUTH.SUCCESS",
  FAIL: "AUTH.FAIL"
};
